// resources/js/react/PolicyReconsentBanner.tsx
/**
 * PolicyReconsentBanner — React companion to the Livewire re-consent banner.
 *
 * Polls the package's consent endpoint to discover whether the current
 * active policy requires re-consent (carried via the `_policy_version`
 * metadata on the consent state). Renders nothing until a stale policy
 * version is detected, then exposes Accept / Review / Dismiss actions.
 *
 * @since 1.0.0
 */

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { getPrivacyClient, type PrivacyClientOptions } from '../privacy';

export interface PolicyReconsentPayload {
	version: string;
	regulation?: string | null;
	url?: string;
}

export interface PolicyReconsentBannerProps extends PrivacyClientOptions {
	policy: PolicyReconsentPayload | null;
	className?: string;
	buttonClassName?: string;
	header?: ReactNode;
	description?: ReactNode;
	footer?: ReactNode;
	labels?: {
		title?: string;
		description?: string;
		review?: string;
		accept?: string;
		dismiss?: string;
	};
	policyUrl?: string;
	reconsentUrl?: string;
	onAccept?: ( version: string ) => void;
	onDismiss?: () => void;
}

export function PolicyReconsentBanner( props: PolicyReconsentBannerProps ): JSX.Element | null {
	const {
		policy,
		className,
		buttonClassName,
		header,
		description,
		footer,
		labels,
		policyUrl = '/privacy/policy',
		reconsentUrl = '/privacy/reconsent',
		onAccept,
		onDismiss,
		...clientOptions
	} = props;

	const client = useMemo( () => getPrivacyClient( clientOptions ), [ clientOptions ] );
	const [ dismissed, setDismissed ] = useState( false );
	const [ saving, setSaving ] = useState( false );

	useEffect( () => {
		setDismissed( false );
	}, [ policy?.version ] );

	if ( null === policy || dismissed ) {
		return null;
	}

	const resolvedLabels = {
		title: labels?.title ?? 'Our privacy policy has been updated',
		description: labels?.description ?? 'Please review the updated policy and confirm that you accept the new terms.',
		review: labels?.review ?? 'Review policy',
		accept: labels?.accept ?? 'Accept updated policy',
		dismiss: labels?.dismiss ?? 'Remind me later',
	};

	const handleAccept = async (): Promise<void> => {
		setSaving( true );
		try {
			const csrf =
				typeof document !== 'undefined'
					? document.querySelector<HTMLMetaElement>( 'meta[name="csrf-token"]' )?.content
					: undefined;
			await fetch( reconsentUrl, {
				method: 'POST',
				headers: {
					Accept: 'application/json',
					'Content-Type': 'application/json',
					...( csrf ? { 'X-CSRF-TOKEN': csrf } : {} ),
				},
				credentials: 'same-origin',
				body: JSON.stringify( {
					version: policy.version,
					regulation: policy.regulation ?? null,
				} ),
			} );
			setDismissed( true );
			onAccept?.( policy.version );
			void client.load();
		} finally {
			setSaving( false );
		}
	};

	const handleDismiss = (): void => {
		setDismissed( true );
		onDismiss?.();
	};

	const buttonClass = buttonClassName ?? 'privacy-reconsent-banner__btn';

	return (
		<div
			role="alertdialog"
			aria-modal="false"
			aria-labelledby="privacy-reconsent-title"
			className={ className ?? 'privacy-reconsent-banner' }
			data-privacy-reconsent
			data-policy-version={ policy.version }
		>
			<div className="privacy-reconsent-banner__inner">
				{ header }
				<h2 id="privacy-reconsent-title">{ resolvedLabels.title }</h2>
				{ description ?? <p>{ resolvedLabels.description }</p> }
				<p className="privacy-reconsent-banner__version">
					Version: <strong>{ policy.version }</strong>
				</p>
				<div className="privacy-reconsent-banner__actions">
					<a
						className={ buttonClass }
						href={ policy.url ?? policyUrl }
						target="_blank"
						rel="noopener noreferrer"
					>
						{ resolvedLabels.review }
					</a>
					<button type="button" className={ buttonClass } disabled={ saving } onClick={ handleDismiss }>
						{ resolvedLabels.dismiss }
					</button>
					<button type="button" className={ `${ buttonClass } btn-primary` } disabled={ saving } onClick={ () => void handleAccept() }>
						{ resolvedLabels.accept }
					</button>
				</div>
				{ footer }
			</div>
		</div>
	);
}

// resources/js/vue/PolicyReconsentBanner.vue
<script setup lang="ts">
/**
 * PolicyReconsentBanner — Vue companion to the Livewire re-consent banner.
 *
 * Render in the application's main layout and feed it the active policy
 * payload (from a shared store, an Inertia prop, or a Livewire bridge).
 * The component renders nothing when `policy` is null.
 *
 * @since 1.0.0
 */

import { computed, ref, watch } from 'vue';
import { getPrivacyClient, type PrivacyClientOptions } from '../privacy';

export interface PolicyReconsentPayload {
	version: string;
	regulation?: string | null;
	url?: string;
}

interface PolicyReconsentBannerProps extends PrivacyClientOptions {
	policy: PolicyReconsentPayload | null;
	className?: string;
	buttonClassName?: string;
	titleLabel?: string;
	descriptionLabel?: string;
	reviewLabel?: string;
	acceptLabel?: string;
	dismissLabel?: string;
	policyUrl?: string;
	reconsentUrl?: string;
}

const props = withDefaults( defineProps<PolicyReconsentBannerProps>(), {
	className: 'privacy-reconsent-banner',
	buttonClassName: 'privacy-reconsent-banner__btn',
	titleLabel: 'Our privacy policy has been updated',
	descriptionLabel: 'Please review the updated policy and confirm that you accept the new terms.',
	reviewLabel: 'Review policy',
	acceptLabel: 'Accept updated policy',
	dismissLabel: 'Remind me later',
	policyUrl: '/privacy/policy',
	reconsentUrl: '/privacy/reconsent',
} );

const emit = defineEmits<{
	( e: 'accept', version: string ): void;
	( e: 'dismiss' ): void;
}>();

const dismissed = ref( false );
const saving = ref( false );

watch(
	() => props.policy?.version,
	() => {
		dismissed.value = false;
	},
);

const visible = computed( () => null !== props.policy && ! dismissed.value );

async function accept(): Promise<void> {
	if ( null === props.policy ) {
		return;
	}
	saving.value = true;
	try {
		const csrf =
			typeof document !== 'undefined'
				? document.querySelector<HTMLMetaElement>( 'meta[name="csrf-token"]' )?.content
				: undefined;
		await fetch( props.reconsentUrl, {
			method: 'POST',
			headers: {
				Accept: 'application/json',
				'Content-Type': 'application/json',
				...( csrf ? { 'X-CSRF-TOKEN': csrf } : {} ),
			},
			credentials: 'same-origin',
			body: JSON.stringify( {
				version: props.policy.version,
				regulation: props.policy.regulation ?? null,
			} ),
		} );
		dismissed.value = true;
		emit( 'accept', props.policy.version );
		const client = getPrivacyClient();
		void client.load();
	} finally {
		saving.value = false;
	}
}

function dismiss(): void {
	dismissed.value = true;
	emit( 'dismiss' );
}
</script>

<template>
	<div
		v-if="visible && policy"
		role="alertdialog"
		aria-modal="false"
		aria-labelledby="privacy-reconsent-title"
		:class="className"
		data-privacy-reconsent
		:data-policy-version="policy.version"
	>
		<div class="privacy-reconsent-banner__inner">
			<slot name="header" />
			<h2 id="privacy-reconsent-title">{{ titleLabel }}</h2>
			<slot name="description">
				<p>{{ descriptionLabel }}</p>
			</slot>
			<p class="privacy-reconsent-banner__version">
				Version: <strong>{{ policy.version }}</strong>
			</p>
			<div class="privacy-reconsent-banner__actions">
				<a
					:class="buttonClassName"
					:href="policy.url ?? policyUrl"
					target="_blank"
					rel="noopener noreferrer"
				>
					{{ reviewLabel }}
				</a>
				<button type="button" :class="buttonClassName" :disabled="saving" @click="dismiss">
					{{ dismissLabel }}
				</button>
				<button
					type="button"
					:class="`${ buttonClassName } btn-primary`"
					:disabled="saving"
					@click="accept"
				>
					{{ acceptLabel }}
				</button>
			</div>
			<slot name="footer" />
		</div>
	</div>
</template>
