// resources/js/vue/VerifyDataRequest.vue
<script setup lang="ts">
/**
 * VerifyDataRequest — Vue identity-verification component.
 *
 * Mirrors the React/Livewire flow: posts the token to the package
 * verification endpoint and surfaces success / expired / error state.
 *
 * @since 1.0.0
 */

import { ref } from 'vue';

interface VerifyDataRequestProps {
	token: string;
	endpoint?: string;
	csrfToken?: string;
	fetchImpl?: typeof fetch;
	className?: string;
	heading?: string;
}

const props = withDefaults( defineProps<VerifyDataRequestProps>(), {
	className: 'privacy-verify-data-request',
	heading: 'Verify your data request',
} );

const emit = defineEmits<{
	( e: 'verified' ): void;
}>();

type Phase = 'idle' | 'pending' | 'success' | 'expired' | 'error';

const phase = ref<Phase>( 'idle' );
const message = ref( '' );

function resolveCsrfToken(): string | undefined {
	if ( typeof document === 'undefined' ) {
		return undefined;
	}

	const meta = document.querySelector<HTMLMetaElement>( 'meta[name="csrf-token"]' );

	return meta?.content;
}

async function submit() {
	if ( phase.value === 'pending' || phase.value === 'success' ) {
		return;
	}

	phase.value = 'pending';
	message.value = '';

	const endpoint = props.endpoint ?? `/privacy/verify/${ encodeURIComponent( props.token ) }`;
	const csrfToken = props.csrfToken ?? resolveCsrfToken();
	const fetchImpl = props.fetchImpl ?? fetch;

	try {
		const headers: Record<string, string> = {
			Accept: 'application/json',
			'X-Requested-With': 'XMLHttpRequest',
		};

		if ( csrfToken ) {
			headers[ 'X-CSRF-TOKEN' ] = csrfToken;
		}

		const response = await fetchImpl( endpoint, {
			method: 'POST',
			headers,
			credentials: 'same-origin',
		} );

		if ( response.status === 410 || response.status === 422 ) {
			phase.value = 'expired';
			message.value = 'This verification link has expired. Please submit a new request.';
			return;
		}

		if ( ! response.ok ) {
			phase.value = 'error';
			message.value = 'We could not verify this request. Please try again.';
			return;
		}

		phase.value = 'success';
		message.value = 'Your identity has been verified and your request is now being processed.';
		emit( 'verified' );
	} catch ( e ) {
		phase.value = 'error';
		message.value = 'We could not reach the verification endpoint.';
	}
}
</script>

<template>
	<div :class="className">
		<h2 v-if="heading" :class="`${ className }__heading`">{{ heading }}</h2>

		<p v-if="phase === 'success'" :class="`${ className }__success`">{{ message }}</p>
		<p v-else-if="phase === 'expired'" :class="`${ className }__error`">{{ message }}</p>
		<p v-else-if="phase === 'error'" :class="`${ className }__error`">{{ message }}</p>

		<button
			v-if="phase !== 'success' && phase !== 'expired'"
			type="button"
			:disabled="phase === 'pending'"
			:class="`${ className }__button`"
			@click="submit"
		>
			{{ phase === 'pending' ? 'Verifying…' : 'Confirm Identity' }}
		</button>
	</div>
</template>

// resources/js/react/VerifyDataRequest.tsx
/**
 * VerifyDataRequest — React identity-verification component.
 *
 * Posts the supplied token to the package's verification endpoint and
 * surfaces the resulting confirmation/expired/already-verified state.
 *
 * @since 1.0.0
 */

import { useState, type ReactNode } from 'react';

export interface VerifyDataRequestProps {
	token: string;
	endpoint?: string;
	csrfToken?: string;
	fetchImpl?: typeof fetch;
	className?: string;
	heading?: ReactNode;
	onVerified?: () => void;
}

type Phase = 'idle' | 'pending' | 'success' | 'expired' | 'error';

function resolveCsrfToken(): string | undefined {
	if ( typeof document === 'undefined' ) {
		return undefined;
	}

	const meta = document.querySelector<HTMLMetaElement>( 'meta[name="csrf-token"]' );

	return meta?.content;
}

export function VerifyDataRequest( props: VerifyDataRequestProps ): JSX.Element {
	const {
		token,
		endpoint = `/privacy/verify/${ encodeURIComponent( token ) }`,
		csrfToken = resolveCsrfToken(),
		fetchImpl = fetch,
		className = 'privacy-verify-data-request',
		heading = 'Verify your data request',
		onVerified,
	} = props;

	const [ phase, setPhase ] = useState<Phase>( 'idle' );
	const [ message, setMessage ] = useState<string>( '' );

	async function submit() {
		if ( phase === 'pending' || phase === 'success' ) {
			return;
		}

		setPhase( 'pending' );
		setMessage( '' );

		try {
			const headers: Record<string, string> = {
				'Accept': 'application/json',
				'X-Requested-With': 'XMLHttpRequest',
			};

			if ( csrfToken ) {
				headers[ 'X-CSRF-TOKEN' ] = csrfToken;
			}

			const response = await fetchImpl( endpoint, {
				method: 'POST',
				headers,
				credentials: 'same-origin',
			} );

			if ( response.status === 410 || response.status === 422 ) {
				setPhase( 'expired' );
				setMessage( 'This verification link has expired. Please submit a new request.' );
				return;
			}

			if ( ! response.ok ) {
				setPhase( 'error' );
				setMessage( 'We could not verify this request. Please try again.' );
				return;
			}

			setPhase( 'success' );
			setMessage( 'Your identity has been verified and your request is now being processed.' );
			onVerified?.();
		} catch ( e ) {
			setPhase( 'error' );
			setMessage( 'We could not reach the verification endpoint.' );
		}
	}

	return (
		<div className={ className }>
			{ heading && <h2 className={ `${ className }__heading` }>{ heading }</h2> }

			{ phase === 'success' && <p className={ `${ className }__success` }>{ message }</p> }
			{ phase === 'expired' && <p className={ `${ className }__error` }>{ message }</p> }
			{ phase === 'error' && <p className={ `${ className }__error` }>{ message }</p> }

			{ phase !== 'success' && phase !== 'expired' && (
				<button
					type="button"
					onClick={ submit }
					disabled={ phase === 'pending' }
					className={ `${ className }__button` }
				>
					{ phase === 'pending' ? 'Verifying…' : 'Confirm Identity' }
				</button>
			) }
		</div>
	);
}
